# Generated by Django 2.1.2 on 2018-11-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('session', models.CharField(max_length=256)),
                ('first_visit', models.DateTimeField(auto_now=True)),
                ('visits', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('continent', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('os', models.CharField(max_length=256)),
                ('browser', models.CharField(max_length=256)),
                ('session', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
